### ISSUE TITLE
请问这个框架和spring boot结合进行系统开发是否可以呢

### ISSUE THREAD

**Issue by rorovic** [ziaochina/mk-demo#1]
你好！很喜欢你的这个框架，请问和spring boot结合进行系统开发是否可以呢？另外如何加入你的这个项目的开发，谢谢！

**Comment by ziaochina** [comment]
spring boot 提供restful api就可以，没有特别的限制。fork项目，修改了pull request就可以了

**Comment by rorovic** [comment]
好的 谢谢！
