### ISSUE TITLE
执行 npm i -g mk-tools的时候报错

### ISSUE THREAD

**Issue by rorovic** [ziaochina/mk-demo#2]
在本地执行 的时候报错
![image](https://user-images.githubusercontent.com/12078430/30948054-f4abe6e2-a43f-11e7-84ba-f7acc639a366.png)

**Comment by rorovic** [comment]
npm ERR! Unexpected end of input at 1:40366
npm ERR! clzgIe6HfrF6txlX5MHBN3NlrM5zwReTVA83DwS4AT/eTaHHGMVHazrxZpLU4E2M5Y4iV

**Comment by ziaochina** [comment]
更新nodejs和npm版本试试

**Comment by rorovic** [comment]
升级后，又安装了一次 貌似是某个json文件里有问题 报错如下

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/8.4.0/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'i',
1 verbose cli   '-g',
1 verbose cli   'mk-tools' ]
2 info using npm@5.4.2
3 info using node@v8.4.0
4 verbose npm-session 2671b28bbf8a88e2
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 http fetch GET 200 https://registry.npmjs.org/mk-tools 15ms (from cache)
8 silly fetchPackageMetaData error for mk-tools@latest Unexpected end of JSON input while parsing near '...GMVHazrxZpLU4E2M5Y4iV'
9 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...GMVHazrxZpLU4E2M5Y4iV'
9 verbose stack     at JSON.parse (<anonymous>)
9 verbose stack     at parseJson (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/node_modules/json-parse-better-errors/index.js:7:17)
9 verbose stack     at consumeBody.call.then.buffer (/usr/local/lib/node_modules/npm/node_modules/pacote/node_modules/make-fetch-happen/node_modules/node-fetch-npm/src/body.js:96:50)
9 verbose stack     at <anonymous>
9 verbose stack     at process._tickCallback (internal/process/next_tick.js:188:7)
10 verbose cwd /Users/dujinyuan/IdeaProjects/mall-metadata-mk
11 verbose Darwin 16.6.0
12 verbose argv "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/bin/npm" "i" "-g" "mk-tools"
13 verbose node v8.4.0
14 verbose npm  v5.4.2
15 error Unexpected end of JSON input while parsing near '...GMVHazrxZpLU4E2M5Y4iV'
16 verbose exit [ 1, true ]

**Comment by ziaochina** [comment]
试试清下npm cache，或者换个同事机器npm 一下看看，我刚才让同事安装了一下没有出错
$ npm cache clean --force

**Comment by ziaochina** [comment]
http fetch GET 200 https://registry.npmjs.org/mk-tools 15ms (from cache)
貌似从cache来的，可能上次install的时候cache的不完整

**Comment by rorovic** [comment]
好的 我试试 可能是我这里网络的问题

**Comment by rorovic** [comment]
安装成功了已经！谢谢 npm cache clean --force 之后 我又多试了几次 应该是这边网络不好！
