### ISSUE TITLE
mk compile website 之后执行 npm start发生的问题

### ISSUE THREAD

**Issue by rorovic** [ziaochina/mk-demo#3]
按照这个步骤执行：
https://ziaochina.github.io/mk-docs/#/mk-app-portal/markdown?id=3 
在npm start这一步执行后，报错如下：
<img width="1144" alt="default" src="https://user-images.githubusercontent.com/12078430/31783550-3d6c0314-b4c4-11e7-86da-33fb980cd2ba.png">

ERROR in ./node_modules/css-loader!./node_modules/less-loader/dist/cjs.js!./assets/styles/index.less
Module build failed:

@import "~antd/lib/style/color/colors";
^
Can't resolve 'antd/lib/style/color/colors' in '/Users/dujinyuan/IdeaProjects/mall-metadata-mk/mall-metadata-pro/node_modules/mk-component/dist/assets/theme'
      in /Users/dujinyuan/IdeaProjects/mall-metadata-mk/mall-metadata-pro/node_modules/mk-component/dist/assets/theme/index.less (line 1, column 0)
 @ ./assets/styles/index.less 4:14-121
 @ multi (webpack)-dev-server/client?http://0.0.0.0:8089 ./index.js ./assets/styles/index.less

**Comment by ziaochina** [comment]
$ sudo npm i -g mk-tools //更新mk-tools
$ mk website www //创建网站重新试试

**Comment by rorovic** [comment]
OK 没问题了 谢谢！
